// Central tool catalog — defines all 40+ tools, their metadata, inputs, and API type.
// Used by the tools hub page and dynamic tool pages.

export type ToolCategory = 'adsense' | 'content' | 'seo' | 'technical' | 'legal' | 'media'
export type ToolType = 'ai' | 'calculator' | 'fetcher'

export interface ToolInput {
  id: string
  label: string
  type: 'text' | 'textarea' | 'url' | 'select' | 'number'
  placeholder?: string
  options?: string[]
  required?: boolean
  rows?: number
  min?: number
  max?: number
  description?: string
}

export interface ToolDef {
  id: string
  name: string
  tagline: string
  description: string
  category: ToolCategory
  type: ToolType
  icon: string  // lucide icon name
  color: string // tailwind bg color class for icon
  textColor: string
  badge?: 'Popular' | 'New' | 'AI'
  inputs: ToolInput[]
  outputLabel?: string
  apiRoute?: string  // override default /api/ai/tools or /api/dev-tools
}

export const TOOL_CATEGORIES: Record<ToolCategory, { label: string; emoji: string; description: string }> = {
  adsense:   { label: 'AdSense Tools',      emoji: '🎯', description: 'Everything you need to get AdSense approved' },
  content:   { label: 'Content & Writing',  emoji: '✍️', description: 'AI-powered writing tools for bloggers' },
  seo:       { label: 'SEO Tools',          emoji: '🔍', description: 'Optimize your site for Google search' },
  technical: { label: 'Developer Tools',    emoji: '🛠️', description: 'Technical checks for websites and domains' },
  legal:     { label: 'Legal & Policy',     emoji: '📄', description: 'Generate legal pages required for AdSense' },
  media:     { label: 'Media & Images',     emoji: '🎨', description: 'Thumbnail and image tools for content creators' },
}

export const ALL_TOOLS: ToolDef[] = [
  // ── ADSENSE ────────────────────────────────────────────────────────────────
  {
    id: 'adsense-checker',
    name: 'Website AdSense Checker',
    tagline: 'Full AI-powered readiness scan',
    description: 'Deep-crawl your website and get a full AI report on AdSense approval readiness, issues, and fix plan.',
    category: 'adsense',
    type: 'fetcher',
    icon: 'Scan',
    color: 'bg-violet-500/15',
    textColor: 'text-violet-400',
    badge: 'Popular',
    apiRoute: '/api/crawl',
    inputs: [{ id: 'url', label: 'Website URL', type: 'url', placeholder: 'https://yourwebsite.com', required: true }],
    outputLabel: 'Full Site Report',
  },
  {
    id: 'article-analyzer',
    name: 'Article Analyzer',
    tagline: 'Check all articles for AdSense risk',
    description: 'Analyze every article on your site for thin content, policy violations, and plagiarism risk.',
    category: 'adsense',
    type: 'fetcher',
    icon: 'FileSearch',
    color: 'bg-blue-500/15',
    textColor: 'text-blue-400',
    badge: 'Popular',
    apiRoute: '/dashboard/articles',
    inputs: [],
  },
  {
    id: 'niche-checker',
    name: 'Niche Profitability Checker',
    tagline: 'Is your niche AdSense-friendly?',
    description: 'Get an AI assessment of your niche\'s AdSense potential, CPC range, competition, and approval risk.',
    category: 'adsense',
    type: 'ai',
    icon: 'Target',
    color: 'bg-emerald-500/15',
    textColor: 'text-emerald-400',
    badge: 'AI',
    inputs: [
      { id: 'niche', label: 'Your Niche / Topic', type: 'text', placeholder: 'e.g., Personal finance for millennials', required: true },
      { id: 'region', label: 'Primary Audience Region', type: 'select', options: ['India', 'USA', 'UK', 'Global', 'Other'] },
    ],
    outputLabel: 'Niche Analysis Report',
  },
  {
    id: 'revenue-estimator',
    name: 'AdSense Revenue Estimator',
    tagline: 'Estimate your AdSense earnings potential',
    description: 'Calculate estimated monthly AdSense revenue based on your traffic, niche, and geographic mix.',
    category: 'adsense',
    type: 'calculator',
    icon: 'DollarSign',
    color: 'bg-amber-500/15',
    textColor: 'text-amber-400',
    badge: 'New',
    inputs: [
      { id: 'monthly_visitors', label: 'Monthly Page Views', type: 'number', placeholder: '10000', required: true, min: 100 },
      { id: 'niche', label: 'Niche / Category', type: 'select', options: ['Finance', 'Technology', 'Health', 'Food & Cooking', 'Travel', 'Education', 'Entertainment', 'Lifestyle', 'News', 'Other'] },
      { id: 'region', label: 'Primary Traffic Region', type: 'select', options: ['USA/UK/AU (Tier 1)', 'India/South Asia (Tier 2)', 'Rest of World (Tier 3)'] },
    ],
    outputLabel: 'Revenue Estimate',
  },
  {
    id: 'cpc-calculator',
    name: 'CPC / RPM Calculator',
    tagline: 'Calculate clicks, earnings, and RPM',
    description: 'Calculate CPC, RPM, CTR, and estimated earnings from your AdSense data.',
    category: 'adsense',
    type: 'calculator',
    icon: 'Calculator',
    color: 'bg-rose-500/15',
    textColor: 'text-rose-400',
    inputs: [
      { id: 'impressions', label: 'Ad Impressions', type: 'number', placeholder: '10000', required: true },
      { id: 'clicks', label: 'Ad Clicks', type: 'number', placeholder: '150', required: true },
      { id: 'earnings', label: 'Total Earnings (₹)', type: 'number', placeholder: '500', required: true },
    ],
    outputLabel: 'Calculated Metrics',
  },
  {
    id: 'eligibility-checklist',
    name: 'AdSense Eligibility Checklist',
    tagline: 'Pre-application readiness check',
    description: 'Step-by-step checklist to verify your site meets all Google AdSense requirements before applying.',
    category: 'adsense',
    type: 'ai',
    icon: 'ClipboardCheck',
    color: 'bg-indigo-500/15',
    textColor: 'text-indigo-400',
    badge: 'New',
    inputs: [
      { id: 'url', label: 'Your Website URL', type: 'url', placeholder: 'https://yoursite.com', required: true },
      { id: 'domain_age_months', label: 'Domain Age (months)', type: 'number', placeholder: '8', required: true },
      { id: 'article_count', label: 'Number of Articles', type: 'number', placeholder: '25', required: true },
      { id: 'avg_word_count', label: 'Average Word Count per Article', type: 'number', placeholder: '1200' },
    ],
    outputLabel: 'Eligibility Report',
  },
  {
    id: 'policy-checker',
    name: 'Content Policy Checker',
    tagline: 'Check for AdSense policy violations',
    description: 'Paste your article text and AI will flag any AdSense policy violation keywords or restricted content.',
    category: 'adsense',
    type: 'ai',
    icon: 'ShieldCheck',
    color: 'bg-red-500/15',
    textColor: 'text-red-400',
    badge: 'AI',
    apiRoute: '/api/ai/content-policy-check',
    inputs: [
      { id: 'content', label: 'Article Content', type: 'textarea', placeholder: 'Paste your article text here...', required: true, rows: 8 },
    ],
    outputLabel: 'Policy Check Results',
  },

  // ── CONTENT & WRITING ─────────────────────────────────────────────────────
  {
    id: 'article-writer',
    name: 'AI Article Writer',
    tagline: 'Generate full blog posts with AI',
    description: 'Generate complete, SEO-optimized blog articles ready for AdSense approval.',
    category: 'content',
    type: 'ai',
    icon: 'PenLine',
    color: 'bg-violet-500/15',
    textColor: 'text-violet-400',
    badge: 'Popular',
    apiRoute: '/dashboard/article-studio',
    inputs: [],
  },
  {
    id: 'blog-intro',
    name: 'Blog Intro Generator',
    tagline: 'Hook readers from the first line',
    description: 'Generate compelling blog introductions that engage readers and improve AdSense session time.',
    category: 'content',
    type: 'ai',
    icon: 'Quote',
    color: 'bg-blue-500/15',
    textColor: 'text-blue-400',
    badge: 'AI',
    inputs: [
      { id: 'topic', label: 'Blog Post Topic', type: 'text', placeholder: 'e.g., How to get AdSense approval in 2025', required: true },
      { id: 'keywords', label: 'Target Keywords', type: 'text', placeholder: 'adsense approval, get approved' },
      { id: 'tone', label: 'Writing Tone', type: 'select', options: ['Informative', 'Conversational', 'Professional', 'Engaging', 'Authoritative'] },
    ],
    outputLabel: 'Blog Introduction',
  },
  {
    id: 'blog-outline',
    name: 'Blog Outline Generator',
    tagline: 'Structure winning blog posts',
    description: 'Generate a detailed H2/H3 outline for any blog topic, optimized for SEO and AdSense content requirements.',
    category: 'content',
    type: 'ai',
    icon: 'List',
    color: 'bg-emerald-500/15',
    textColor: 'text-emerald-400',
    badge: 'AI',
    inputs: [
      { id: 'topic', label: 'Blog Topic', type: 'text', placeholder: 'e.g., Best ways to increase AdSense RPM', required: true },
      { id: 'word_count', label: 'Target Word Count', type: 'select', options: ['500-800', '800-1200', '1200-2000', '2000-3000', '3000+'] },
      { id: 'audience', label: 'Target Audience', type: 'text', placeholder: 'e.g., beginner bloggers in India' },
    ],
    outputLabel: 'Blog Outline',
  },
  {
    id: 'faq-generator',
    name: 'FAQ Generator',
    tagline: 'Add FAQ schema and rank higher',
    description: 'Generate 5-10 FAQ questions and answers for any topic, with JSON-LD schema markup included.',
    category: 'content',
    type: 'ai',
    icon: 'HelpCircle',
    color: 'bg-amber-500/15',
    textColor: 'text-amber-400',
    badge: 'AI',
    inputs: [
      { id: 'topic', label: 'Topic / Article Title', type: 'text', placeholder: 'e.g., AdSense approval for WordPress', required: true },
      { id: 'count', label: 'Number of FAQs', type: 'select', options: ['5', '8', '10', '15'] },
    ],
    outputLabel: 'FAQ + JSON-LD Schema',
  },
  {
    id: 'cta-generator',
    name: 'CTA Generator',
    tagline: 'Calls-to-action that convert',
    description: 'Generate compelling calls-to-action for any blog post, landing page, or newsletter.',
    category: 'content',
    type: 'ai',
    icon: 'Megaphone',
    color: 'bg-rose-500/15',
    textColor: 'text-rose-400',
    badge: 'AI',
    inputs: [
      { id: 'goal', label: 'Conversion Goal', type: 'text', placeholder: 'e.g., Get readers to sign up for newsletter', required: true },
      { id: 'context', label: 'Page / Article Context', type: 'text', placeholder: 'e.g., Article about AdSense tips' },
      { id: 'style', label: 'CTA Style', type: 'select', options: ['Button text', 'Paragraph CTA', 'Popup CTA', 'Email CTA'] },
    ],
    outputLabel: 'CTA Variations',
  },
  {
    id: 'summarizer',
    name: 'Text Summarizer',
    tagline: 'Summarize long articles instantly',
    description: 'Paste any long article and get a concise, accurate summary in seconds.',
    category: 'content',
    type: 'ai',
    icon: 'AlignLeft',
    color: 'bg-indigo-500/15',
    textColor: 'text-indigo-400',
    inputs: [
      { id: 'content', label: 'Article / Text to Summarize', type: 'textarea', placeholder: 'Paste your article here...', required: true, rows: 8 },
      { id: 'length', label: 'Summary Length', type: 'select', options: ['1 paragraph', '3 bullet points', '5 bullet points', '2 paragraphs'] },
    ],
    outputLabel: 'Summary',
  },
  {
    id: 'content-expander',
    name: 'Content Expander',
    tagline: 'Expand thin content instantly',
    description: 'Paste thin or short content and AI will expand it into a detailed, AdSense-ready article section.',
    category: 'content',
    type: 'ai',
    icon: 'Expand',
    color: 'bg-teal-500/15',
    textColor: 'text-teal-400',
    badge: 'AI',
    inputs: [
      { id: 'content', label: 'Content to Expand', type: 'textarea', placeholder: 'Paste your thin content here...', required: true, rows: 5 },
      { id: 'target_words', label: 'Target Word Count', type: 'select', options: ['300 words', '500 words', '800 words', '1000+ words'] },
    ],
    outputLabel: 'Expanded Content',
  },
  {
    id: 'paragraph-rewriter',
    name: 'Paragraph Rewriter',
    tagline: 'Rewrite for originality & clarity',
    description: 'Rewrite any paragraph to improve readability, originality, and AdSense policy compliance.',
    category: 'content',
    type: 'ai',
    icon: 'RefreshCw',
    color: 'bg-orange-500/15',
    textColor: 'text-orange-400',
    apiRoute: '/api/ai/rewrite',
    inputs: [
      { id: 'content', label: 'Text to Rewrite', type: 'textarea', placeholder: 'Paste text to rewrite...', required: true, rows: 5 },
      { id: 'style', label: 'Rewrite Style', type: 'select', options: ['Improve clarity', 'Make more engaging', 'Make more formal', 'Simplify', 'Expand detail'] },
    ],
    outputLabel: 'Rewritten Content',
  },
  {
    id: 'headline-analyzer',
    name: 'Headline Analyzer',
    tagline: 'Score and improve your headlines',
    description: 'Analyze your blog post headline for SEO, emotional impact, and click-through potential.',
    category: 'content',
    type: 'ai',
    icon: 'Heading',
    color: 'bg-pink-500/15',
    textColor: 'text-pink-400',
    badge: 'New',
    inputs: [
      { id: 'headline', label: 'Your Headline', type: 'text', placeholder: 'e.g., 10 Ways to Get AdSense Approved Fast', required: true },
      { id: 'niche', label: 'Article Niche', type: 'text', placeholder: 'e.g., blogging, finance, health' },
    ],
    outputLabel: 'Headline Analysis',
  },

  // ── SEO TOOLS ─────────────────────────────────────────────────────────────
  {
    id: 'meta-generator',
    name: 'Meta Tag Generator',
    tagline: 'Generate title tags & meta descriptions',
    description: 'Generate optimized meta title and description tags for any page.',
    category: 'seo',
    type: 'ai',
    icon: 'Tag',
    color: 'bg-blue-500/15',
    textColor: 'text-blue-400',
    badge: 'Popular',
    apiRoute: '/api/ai/meta-generator',
    inputs: [
      { id: 'topic', label: 'Page Topic / Title', type: 'text', placeholder: 'e.g., How to get AdSense approval', required: true },
      { id: 'keywords', label: 'Target Keywords', type: 'text', placeholder: 'adsense approval, adsense checker' },
    ],
    outputLabel: 'Meta Tags',
  },
  {
    id: 'title-generator',
    name: 'Blog Title Generator',
    tagline: 'Generate SEO-optimized post titles',
    description: 'Generate 10 SEO-optimized blog post title ideas for any topic.',
    category: 'seo',
    type: 'ai',
    icon: 'Heading',
    color: 'bg-violet-500/15',
    textColor: 'text-violet-400',
    badge: 'Popular',
    apiRoute: '/api/ai/title-generator',
    inputs: [
      { id: 'topic', label: 'Blog Topic', type: 'text', placeholder: 'e.g., Google AdSense tips for beginners', required: true },
      { id: 'style', label: 'Title Style', type: 'select', options: ['How-to', 'Listicle', 'Question', 'Guide', 'Mixed'] },
    ],
    outputLabel: 'Title Ideas',
  },
  {
    id: 'keyword-density',
    name: 'Keyword Density Checker',
    tagline: 'Check keyword stuffing risk',
    description: 'Analyze keyword density in your content to avoid over-optimization penalties.',
    category: 'seo',
    type: 'ai',
    icon: 'BarChart3',
    color: 'bg-emerald-500/15',
    textColor: 'text-emerald-400',
    apiRoute: '/api/ai/keyword-density',
    inputs: [
      { id: 'content', label: 'Article Content', type: 'textarea', placeholder: 'Paste your article...', required: true, rows: 6 },
      { id: 'target_keyword', label: 'Target Keyword', type: 'text', placeholder: 'e.g., adsense approval' },
    ],
    outputLabel: 'Keyword Density Report',
  },
  {
    id: 'seo-suggestions',
    name: 'SEO Suggestions',
    tagline: 'AI-powered SEO improvement tips',
    description: 'Get actionable SEO improvement suggestions for any article or page.',
    category: 'seo',
    type: 'ai',
    icon: 'TrendingUp',
    color: 'bg-amber-500/15',
    textColor: 'text-amber-400',
    apiRoute: '/api/ai/seo-suggestions',
    inputs: [
      { id: 'url', label: 'Article URL', type: 'url', placeholder: 'https://yoursite.com/article', required: true },
    ],
    outputLabel: 'SEO Suggestions',
  },
  {
    id: 'schema-generator',
    name: 'Schema Markup Generator',
    tagline: 'JSON-LD schema for rich results',
    description: 'Generate Schema.org JSON-LD markup for articles, FAQs, how-tos, and more.',
    category: 'seo',
    type: 'ai',
    icon: 'Code2',
    color: 'bg-indigo-500/15',
    textColor: 'text-indigo-400',
    badge: 'New',
    inputs: [
      { id: 'type', label: 'Schema Type', type: 'select', options: ['Article', 'FAQ', 'HowTo', 'BlogPosting', 'Product', 'LocalBusiness', 'Review', 'Recipe', 'Course'], required: true },
      { id: 'title', label: 'Page Title', type: 'text', placeholder: 'e.g., How to Get AdSense Approved', required: true },
      { id: 'description', label: 'Page Description', type: 'textarea', placeholder: 'Brief description of the page...', rows: 3 },
      { id: 'url', label: 'Page URL', type: 'url', placeholder: 'https://yoursite.com/page' },
    ],
    outputLabel: 'JSON-LD Schema Code',
  },
  {
    id: 'og-generator',
    name: 'Open Graph Tag Generator',
    tagline: 'Perfect social media previews',
    description: 'Generate Open Graph meta tags for Facebook, LinkedIn, and social sharing.',
    category: 'seo',
    type: 'ai',
    icon: 'Share2',
    color: 'bg-blue-500/15',
    textColor: 'text-blue-400',
    badge: 'New',
    inputs: [
      { id: 'title', label: 'Page Title', type: 'text', placeholder: 'Your page title', required: true },
      { id: 'description', label: 'Page Description', type: 'textarea', placeholder: 'Page description...', rows: 2, required: true },
      { id: 'url', label: 'Page URL', type: 'url', placeholder: 'https://yoursite.com/page', required: true },
      { id: 'image_url', label: 'OG Image URL (optional)', type: 'url', placeholder: 'https://yoursite.com/image.jpg' },
    ],
    outputLabel: 'Open Graph Tags',
  },
  {
    id: 'twitter-card',
    name: 'Twitter Card Generator',
    tagline: 'Rich previews on X / Twitter',
    description: 'Generate Twitter Card meta tags for better visibility when shared on Twitter/X.',
    category: 'seo',
    type: 'ai',
    icon: 'Twitter',
    color: 'bg-sky-500/15',
    textColor: 'text-sky-400',
    badge: 'New',
    inputs: [
      { id: 'title', label: 'Title', type: 'text', placeholder: 'Your page title', required: true },
      { id: 'description', label: 'Description', type: 'textarea', placeholder: 'Short description...', rows: 2, required: true },
      { id: 'card_type', label: 'Card Type', type: 'select', options: ['summary', 'summary_large_image', 'app'] },
      { id: 'site_handle', label: 'Twitter Handle (@)', type: 'text', placeholder: '@yourtwitterhandle' },
    ],
    outputLabel: 'Twitter Card Tags',
  },
  {
    id: 'readability',
    name: 'Readability Checker',
    tagline: 'Flesch-Kincaid score + suggestions',
    description: 'Check how readable your content is and get suggestions to improve clarity and engagement.',
    category: 'seo',
    type: 'ai',
    icon: 'BookOpen',
    color: 'bg-teal-500/15',
    textColor: 'text-teal-400',
    inputs: [
      { id: 'content', label: 'Article Content', type: 'textarea', placeholder: 'Paste your article text...', required: true, rows: 7 },
    ],
    outputLabel: 'Readability Report',
  },
  {
    id: 'word-count',
    name: 'Word Count Tool',
    tagline: 'Count words, chars, reading time',
    description: 'Instantly count words, characters, sentences, paragraphs and estimate reading time.',
    category: 'seo',
    type: 'calculator',
    icon: 'Hash',
    color: 'bg-gray-500/15',
    textColor: 'text-gray-400',
    inputs: [
      { id: 'content', label: 'Your Text', type: 'textarea', placeholder: 'Paste any text here...', required: true, rows: 8 },
    ],
    outputLabel: 'Word Count Stats',
  },
  {
    id: 'hreflang',
    name: 'hreflang Tag Generator',
    tagline: 'Multi-language SEO tags',
    description: 'Generate hreflang tags for multilingual websites to tell Google which language to show in each country.',
    category: 'seo',
    type: 'ai',
    icon: 'Globe',
    color: 'bg-violet-500/15',
    textColor: 'text-violet-400',
    badge: 'New',
    inputs: [
      { id: 'pages', label: 'Page URLs (one per line)', type: 'textarea', placeholder: 'https://example.com/en/page\nhttps://example.com/hi/page\nhttps://example.com/es/page', required: true, rows: 5, description: 'Include all language variants of the same page' },
      { id: 'langs', label: 'Languages (one per line, matching URLs)', type: 'textarea', placeholder: 'en\nhi\nes', required: true, rows: 5 },
    ],
    outputLabel: 'hreflang Tags',
  },

  // ── TECHNICAL / DEVELOPER ─────────────────────────────────────────────────
  {
    id: 'http-headers',
    name: 'HTTP Header Checker',
    tagline: 'Inspect HTTP response headers',
    description: 'Fetch and display all HTTP response headers for any URL. Check cache, security headers, redirects.',
    category: 'technical',
    type: 'fetcher',
    icon: 'Server',
    color: 'bg-slate-500/15',
    textColor: 'text-slate-400',
    badge: 'New',
    inputs: [{ id: 'url', label: 'URL to Check', type: 'url', placeholder: 'https://example.com', required: true }],
    outputLabel: 'HTTP Headers',
  },
  {
    id: 'redirect-checker',
    name: 'Redirect Chain Checker',
    tagline: 'Trace the full redirect chain',
    description: 'Follow all HTTP redirects for a URL and show the complete chain (301, 302, etc.) with status codes.',
    category: 'technical',
    type: 'fetcher',
    icon: 'ArrowLeftRight',
    color: 'bg-orange-500/15',
    textColor: 'text-orange-400',
    badge: 'New',
    inputs: [{ id: 'url', label: 'URL to Trace', type: 'url', placeholder: 'https://example.com/old-page', required: true }],
    outputLabel: 'Redirect Chain',
  },
  {
    id: 'ssl-checker',
    name: 'SSL Certificate Checker',
    tagline: 'Check HTTPS & certificate validity',
    description: 'Verify SSL certificate status, expiry date, issuer, and HTTPS configuration for any domain.',
    category: 'technical',
    type: 'fetcher',
    icon: 'Lock',
    color: 'bg-green-500/15',
    textColor: 'text-green-400',
    badge: 'New',
    inputs: [{ id: 'domain', label: 'Domain', type: 'text', placeholder: 'example.com (without https://)', required: true }],
    outputLabel: 'SSL Report',
  },
  {
    id: 'domain-age',
    name: 'Domain Age Checker',
    tagline: 'Check when a domain was registered',
    description: 'Look up WHOIS data to find domain registration date, age, and registrar information.',
    category: 'technical',
    type: 'fetcher',
    icon: 'Calendar',
    color: 'bg-indigo-500/15',
    textColor: 'text-indigo-400',
    apiRoute: '/api/whois',
    inputs: [{ id: 'domain', label: 'Domain', type: 'text', placeholder: 'example.com', required: true }],
    outputLabel: 'Domain Info',
  },
  {
    id: 'ads-txt',
    name: 'Ads.txt Validator',
    tagline: 'Validate your ads.txt file',
    description: 'Check if your ads.txt file exists, is properly formatted, and contains your AdSense publisher ID.',
    category: 'technical',
    type: 'fetcher',
    icon: 'FileCode',
    color: 'bg-amber-500/15',
    textColor: 'text-amber-400',
    badge: 'New',
    inputs: [
      { id: 'domain', label: 'Website Domain', type: 'text', placeholder: 'example.com', required: true },
      { id: 'pub_id', label: 'AdSense Publisher ID (optional)', type: 'text', placeholder: 'ca-pub-1234567890123456', description: 'We\'ll check if your pub-ID is present' },
    ],
    outputLabel: 'Ads.txt Report',
  },
  {
    id: 'robots-tester',
    name: 'Robots.txt Tester',
    tagline: 'Check if Google can crawl your pages',
    description: 'Fetch and analyze your robots.txt file. Test if specific URLs are blocked or allowed.',
    category: 'technical',
    type: 'fetcher',
    icon: 'Bot',
    color: 'bg-rose-500/15',
    textColor: 'text-rose-400',
    inputs: [
      { id: 'domain', label: 'Website Domain', type: 'text', placeholder: 'example.com', required: true },
      { id: 'test_url', label: 'URL to Test (optional)', type: 'text', placeholder: '/category/finance/', description: 'Test if this path is blocked' },
    ],
    outputLabel: 'Robots.txt Analysis',
  },
  {
    id: 'sitemap-validator',
    name: 'Sitemap Validator',
    tagline: 'Verify your XML sitemap',
    description: 'Check if your sitemap.xml exists, is valid XML, and contains proper URLs.',
    category: 'technical',
    type: 'fetcher',
    icon: 'Map',
    color: 'bg-teal-500/15',
    textColor: 'text-teal-400',
    inputs: [{ id: 'url', label: 'Sitemap URL', type: 'url', placeholder: 'https://example.com/sitemap.xml', required: true }],
    outputLabel: 'Sitemap Report',
  },
  {
    id: 'canonical-checker',
    name: 'Canonical Tag Checker',
    tagline: 'Check for duplicate content issues',
    description: 'Check if a page has a canonical tag and whether it points to the correct URL.',
    category: 'technical',
    type: 'fetcher',
    icon: 'Link',
    color: 'bg-blue-500/15',
    textColor: 'text-blue-400',
    badge: 'New',
    inputs: [{ id: 'url', label: 'Page URL', type: 'url', placeholder: 'https://example.com/page', required: true }],
    outputLabel: 'Canonical Check',
  },
  {
    id: 'json-ld-validator',
    name: 'JSON-LD Validator',
    tagline: 'Validate structured data markup',
    description: 'Paste JSON-LD schema and validate it for syntax errors and Schema.org compliance.',
    category: 'technical',
    type: 'ai',
    icon: 'Braces',
    color: 'bg-purple-500/15',
    textColor: 'text-purple-400',
    badge: 'New',
    inputs: [
      { id: 'jsonld', label: 'JSON-LD Code', type: 'textarea', placeholder: '{\n  "@context": "https://schema.org",\n  "@type": "Article",\n  ...\n}', required: true, rows: 10 },
    ],
    outputLabel: 'Validation Results',
  },
  {
    id: 'whois-lookup',
    name: 'WHOIS Lookup',
    tagline: 'Full domain registration details',
    description: 'Get complete WHOIS information including registrar, registrant, name servers, and expiry date.',
    category: 'technical',
    type: 'fetcher',
    icon: 'Search',
    color: 'bg-gray-500/15',
    textColor: 'text-gray-400',
    apiRoute: '/api/whois',
    inputs: [{ id: 'domain', label: 'Domain Name', type: 'text', placeholder: 'example.com', required: true }],
    outputLabel: 'WHOIS Data',
  },
  {
    id: 'robots-generator',
    name: 'Robots.txt Generator',
    tagline: 'Build the perfect robots.txt',
    description: 'Generate a properly configured robots.txt file for your website.',
    category: 'technical',
    type: 'ai',
    icon: 'FileText',
    color: 'bg-yellow-500/15',
    textColor: 'text-yellow-400',
    badge: 'New',
    inputs: [
      { id: 'cms', label: 'CMS / Platform', type: 'select', options: ['WordPress', 'Blogger', 'Next.js', 'Wix', 'Squarespace', 'Custom/Other'] },
      { id: 'block_pages', label: 'Pages to Block (optional)', type: 'textarea', placeholder: '/wp-admin/\n/wp-login.php\n/private/', rows: 4 },
      { id: 'sitemap_url', label: 'Sitemap URL', type: 'url', placeholder: 'https://example.com/sitemap.xml' },
    ],
    outputLabel: 'robots.txt File',
  },
  {
    id: 'sitemap-generator',
    name: 'Sitemap Generator Guide',
    tagline: 'Setup sitemap for your CMS',
    description: 'Get step-by-step instructions to create and submit an XML sitemap for your CMS.',
    category: 'technical',
    type: 'ai',
    icon: 'Network',
    color: 'bg-indigo-500/15',
    textColor: 'text-indigo-400',
    inputs: [
      { id: 'cms', label: 'Your CMS / Platform', type: 'select', options: ['WordPress', 'Blogger', 'Next.js / React', 'Hugo', 'Jekyll', 'Wix', 'Squarespace', 'Custom HTML'] },
    ],
    outputLabel: 'Sitemap Setup Guide',
  },

  // ── LEGAL & POLICY ────────────────────────────────────────────────────────
  {
    id: 'privacy-policy',
    name: 'Privacy Policy Generator',
    tagline: 'Required for AdSense approval',
    description: 'Generate a complete, Google AdSense-compliant Privacy Policy for your website.',
    category: 'legal',
    type: 'ai',
    icon: 'Shield',
    color: 'bg-violet-500/15',
    textColor: 'text-violet-400',
    badge: 'Popular',
    apiRoute: '/api/ai/privacy-policy',
    inputs: [
      { id: 'site_name', label: 'Website Name', type: 'text', placeholder: 'My Blog', required: true },
      { id: 'site_url', label: 'Website URL', type: 'url', placeholder: 'https://myblog.com', required: true },
      { id: 'email', label: 'Contact Email', type: 'text', placeholder: 'contact@myblog.com', required: true },
    ],
    outputLabel: 'Privacy Policy',
  },
  {
    id: 'tos-generator',
    name: 'Terms of Service Generator',
    tagline: 'Protect your website legally',
    description: 'Generate a comprehensive Terms of Service page for your website or blog.',
    category: 'legal',
    type: 'ai',
    icon: 'ScrollText',
    color: 'bg-blue-500/15',
    textColor: 'text-blue-400',
    badge: 'New',
    inputs: [
      { id: 'site_name', label: 'Website Name', type: 'text', placeholder: 'My Blog', required: true },
      { id: 'site_url', label: 'Website URL', type: 'url', placeholder: 'https://myblog.com', required: true },
      { id: 'email', label: 'Contact Email', type: 'text', placeholder: 'contact@myblog.com', required: true },
      { id: 'type', label: 'Website Type', type: 'select', options: ['Blog / Content Site', 'E-Commerce', 'SaaS / App', 'Forum / Community', 'Portfolio'] },
    ],
    outputLabel: 'Terms of Service',
  },
  {
    id: 'disclaimer-generator',
    name: 'Disclaimer Generator',
    tagline: 'Recommended for most niches',
    description: 'Generate affiliate disclaimer, medical disclaimer, or general disclaimer text for your site.',
    category: 'legal',
    type: 'ai',
    icon: 'AlertCircle',
    color: 'bg-amber-500/15',
    textColor: 'text-amber-400',
    badge: 'New',
    inputs: [
      { id: 'site_name', label: 'Website Name', type: 'text', placeholder: 'My Blog', required: true },
      { id: 'type', label: 'Disclaimer Type', type: 'select', options: ['Affiliate Disclaimer', 'Medical Disclaimer', 'Legal Disclaimer', 'Financial Disclaimer', 'General Disclaimer'] },
      { id: 'niche', label: 'Website Niche', type: 'text', placeholder: 'e.g., health, finance, technology' },
    ],
    outputLabel: 'Disclaimer Text',
  },
  {
    id: 'cookie-policy',
    name: 'Cookie Policy Generator',
    tagline: 'GDPR & AdSense cookie compliance',
    description: 'Generate a cookie policy that satisfies GDPR requirements and AdSense cookie disclosure.',
    category: 'legal',
    type: 'ai',
    icon: 'Cookie',
    color: 'bg-orange-500/15',
    textColor: 'text-orange-400',
    badge: 'New',
    inputs: [
      { id: 'site_name', label: 'Website Name', type: 'text', placeholder: 'My Blog', required: true },
      { id: 'site_url', label: 'Website URL', type: 'url', placeholder: 'https://myblog.com', required: true },
      { id: 'uses_adsense', label: 'Uses AdSense?', type: 'select', options: ['Yes', 'No', 'Planning to'] },
      { id: 'uses_analytics', label: 'Uses Google Analytics?', type: 'select', options: ['Yes', 'No'] },
    ],
    outputLabel: 'Cookie Policy',
  },

  // ── MEDIA ────────────────────────────────────────────────────────────────
  {
    id: 'thumbnail-generator',
    name: 'Thumbnail Generator',
    tagline: 'AI-generated blog thumbnails',
    description: 'Generate eye-catching blog post thumbnails using AI. Perfect for increasing click-through rates.',
    category: 'media',
    type: 'ai',
    icon: 'Image',
    color: 'bg-pink-500/15',
    textColor: 'text-pink-400',
    badge: 'Popular',
    apiRoute: '/dashboard/ai-tools',
    inputs: [],
  },
  {
    id: 'alt-text',
    name: 'Image Alt Text Generator',
    tagline: 'Improve accessibility and SEO',
    description: 'Generate descriptive, SEO-optimized alt text for your blog images.',
    category: 'media',
    type: 'ai',
    icon: 'ImageIcon',
    color: 'bg-violet-500/15',
    textColor: 'text-violet-400',
    badge: 'New',
    inputs: [
      { id: 'image_context', label: 'Describe your image', type: 'textarea', placeholder: 'e.g., A laptop on a wooden desk with a cup of coffee and a notepad', required: true, rows: 3 },
      { id: 'article_topic', label: 'Article Topic', type: 'text', placeholder: 'e.g., work from home productivity tips' },
    ],
    outputLabel: 'Alt Text Options',
  },
]

// Helpers
export function getToolById(id: string): ToolDef | undefined {
  return ALL_TOOLS.find(t => t.id === id)
}

export function getToolsByCategory(category: ToolCategory): ToolDef[] {
  return ALL_TOOLS.filter(t => t.category === category)
}

export function searchTools(query: string): ToolDef[] {
  const q = query.toLowerCase()
  return ALL_TOOLS.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.tagline.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.category.includes(q)
  )
}
